# Generated by Django 2.1.5 on 2022-05-16 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0006_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
